# Generated by Django 5.2.4 on 2025-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("drug", "Medical Drug"),
                            ("supply", "Health Supply"),
                            ("device", "Medical Device"),
                            ("other", "Other"),
                        ],
                        default="drug",
                        max_length=50,
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("strength", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
