# Generated by Django 5.2.4 on 2025-09-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0002_inventoryitem"),
        ("orders", "0002_remove_orderitem_drug_orderitem_item"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Drug",
        ),
    ]
