# Generated by Django 5.2.4 on 2025-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitem_drug_orderitem_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Patient delivery location or address",
                max_length=255,
                null=True,
            ),
        ),
    ]
