# Generated by Django 5.2.4 on 2025-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="illness_categories",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="specialty",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
